### ISSUE TITLE
NullReferenceException in Designmode

### ISSUE THREAD

**Issue by Spy-Shifty** [adambarath/SmithHtmlEditor#2]
Hi there,

I get a NullReferenceException in Designmode

I just followed you instructions:

```
xmlns:smith="clr-namespace:Smith.WPF.HtmlEditor;assembly=Smith.WPF.HtmlEditor"
...
 <smith:HtmlEditor x:Name="htmlEditor" />
```

NullReferenceException :
Smith.WPF.HtmlEditor.HtmlEditor.OnTimerTick(Object sender, EventArgs e)
   bei System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Spy-Shifty** [comment]
Short note: I use the NuGet Version:  1.0.0

**Comment by stevenkc** [comment]
I got the same message

**Comment by Mywk** [comment]
To all of you having this problem, simply add the COM reference "Microsoft HTML Object Library" and it will work flawlessly.

![image](https://user-images.githubusercontent.com/5620014/124361718-d0874900-dc30-11eb-8a62-3bf8e6f4ed2f.png)

**Comment by DarrenNavitas** [comment]
I'm having the same issue - tried adding the COM library mentioned above - and still have the same issue.
Errors immediately at runtime too.

**Comment by adambarath** [comment]
Could you try to run the demo project? Does it work properly on your machine?
May I ask you kindly to share your .csproj file?

**Comment by adambarath** [comment]
> To all of you having this problem, simply add the COM reference "Microsoft HTML Object Library" and it will work flawlessly.
> 
> ![image](https://user-images.githubusercontent.com/5620014/124361718-d0874900-dc30-11eb-8a62-3bf8e6f4ed2f.png)

Or you can do it manually by editing your csproj file:
Reference example:
```
  <ItemGroup>
    <COMReference Include="MSHTML.dll">
      <Guid>3050f1c5-98b5-11cf-bb82-00aa00bdce0b</Guid>
      <VersionMajor>4</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <WrapperTool>tlbimp</WrapperTool>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
  </ItemGroup>
```

**Comment by adambarath** [comment]
> Short note: I use the NuGet Version: 1.0.0

I am sorry but you have to bump it to the latest version. 1.0.0 does not contain fix for NullReferenceException.
